name: Build LaTeX Resume

on:
  push:
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume_01.tex 
          
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: Suyash-Resume
          path: resume_01.pdf 